
development:
  adapter: postgresql
  encoding: unicode
  database: doodles_rest_development
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: sinaraarliss
  password:
  timeout: 5000
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: doodles_rest_test
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: sinaraarliss
  password:
  timeout: 5000
  host: localhost