
development:
  adapter: postgresql
  encoding: unicode
  database: doodles_rest
  pool: 5
  username: sinaraarliss
  password:
  timeout: 5000
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: doodles_rest
  pool: 5
  username: sinaraarliss
  password:
  timeout: 5000
  host: localhost