default: &default
  adapter: postgresql
  encoding: unicode
  database: doodles_rest_development
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: sinaraarliss
  password:
  timeout: 5000

development:
  <<: *default
  adapter: postgresql
  encoding: unicode
  database: doodles_rest_development
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: sinaraarliss
  password:
  timeout: 5000

test:
  <<: *default
  adapter: postgresql
  encoding: unicode
  database: doodles_rest_test
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: sinaraarliss
  password:
  timeout: 5000

production:
  <<: *default
  adapter: postgresql
  encoding: unicode
  database: doodles_rest_production
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: sinaraarliss
  password:
  timeout: 5000